@baseUrl = http://localhost:5000/api

### AUTH ROUTES

# --- Register ---
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "password123"
}

###

# --- LOGIN ---
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "abuchohan@hotmail.co.uk",
  "password": "password123"
}


### 


# --- Logout ---
POST {{baseUrl}}/auth/logout
Content-Type: application/json

###

# --- Reset Password ---
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json

{
    "email": "test@example.com"
}

###


# --- Reset Password ---
POST {{baseUrl}}/auth/reset-password/02f98e3173e6285cf7632a4f21f849934ad1a374df9edef33d488fdd027a8ab2
Content-Type: application/json

{
    "password": "password123"
}

###





# --- me ---
GET {{baseUrl}}/auth/me
Content-Type: application/json
Cookie: session_id=0657d326-ae46-4b75-b076-e1df2c69aff6

###


# --- me ---
GET {{baseUrl}}/users
Content-Type: application/json

###

POST {{baseUrl}}/voice-notes/upload-url
Content-Type: application/json
Cookie: session_id=0657d326-ae46-4b75-b076-e1df2c69aff6

{
  "contentType": "audio/webm"
}

###

GET {{baseUrl}}/voice-notes
Content-Type: application/json
Cookie: session_id=78b773a6-b2d7-4d4e-9c39-8960e66af61a

{
  "contentType": "audio/webm"
}





